Adding core server functions
egordunaev/meteoweb pull request #1
Opened 2019-11-24 20:10 UTC by egordunaev

2019-11-24 21:00 UTC, jskonst requested changes

2019-11-24 21:00 UTC, jskonst commented on db/db.py
> +        self.client = MongoClient('localhost', 27017)
Use configuration to store information about connection - both port and host

2019-11-24 21:00 UTC, jskonst commented on server/app.py
> +@app.route('/get-weather/<country>/<city>')
this 2 methods looks very similar... try to use factory method nj switch between behavior

2019-11-24 21:09 UTC, egordunaev commented on server/app.py
> +@app.route('/get-weather/<country>/<city>')
This was used for gismeteo parsing, since i won't use it (for now and probably never) i wanted to remove this part (and of course i forgot)

2019-11-25 10:10 UTC, jskonst commented
Will take a look

2019-12-18 17:11 UTC, egordunaev commented
Merging server and scheduling

2019-12-18 17:11 UTC, merged